export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';

export const REMOVE_CLIENTS_REQUEST = 'REMOVE_CLIENTS_REQUEST';

export const SET_SELECTED_CLIENT = 'SET_SELECTED_CLIENT';
export const UPDATE_SELECTED_CLIENT ='UPDATE_SELECTED_CLIENT';
export const CLEAR_SELECTED_CLIENT ='CLEAR_SELECTED_CLIENT';